### PR TITLE
Redirect logs from node-binance-api

### PR DESCRIPTION
**Pull request by vaielab**
As discussed in #90, it would be great if we could catch the logs and error made from node-binance-api
In the binance.options there are now 2 more variable onLogs and onError, both are function, by default set to a simple console.log/console.error so it would not change anything.
But if a user want to save them, or ignore them completly, he could override the functions.

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Thank you very much

**Comment by jaggedsoft** [comment]
On second thought, do you think it would make sense to just have one log function instead of two?
I'm not sure the error part is necessary, we can just switch everything to log

Just want your permission then I would like to make that change to make it cleaner

**Comment by vaielab** [comment]
No problem about it, I just saw that you are using console.log and console.error, so I made 2 functions based on that, but for my need, either one is perfect.

**Comment by jaggedsoft** [comment]
Thank you again I love this
I set it to `options.log` in https://github.com/jaggedsoft/node-binance-api/commit/c89b9d2a30d881b04f718b9569c36c611179dd55

**Pull request merged**
