### PR TITLE
make naming more consistent

### PR DESCRIPTION
**Pull request by dmitriz**
I found it confusing to access `aggTrades` under `trades`, 
since there is another stream called `trades`.

### CODE REVIEW

**Comment by jaggedsoft** [comment]
While I agree with what you say, it would be unfair to break everyone's code who has been using this for the past year, and add more confusion by renaming it something else

**Comment by dmzoneill** [comment]
I agree with jon.. however middle ground could possibly be to Put in a stub redirect.

```
Function oldfunction()
{ 
      Console.log ('this function is being eold for newFubction in 0.6. Please update your code');
     Return newFunction ()
}

Function newFunction ()
{
   Return xyz;
}
```

**Comment by dmitriz** [comment]
I see. 
Maybe I need to understand why it was named that way in first place,
diverging from Binance official terms.

**Comment by jaggedsoft** [comment]
Well until recently aggTrades was the only websocket endpoint
They just recently added this one
image

Anyway I am open to renaming this. But perhaps we can figure out a reasonable solution that will work for 30,000+ existing users of the codebase

**Comment by jaggedsoft** [comment]
You are right it does diverge from binance official terms
it should be called aggTrades

image

**Comment by jaggedsoft** [comment]
aggTrade was called trade because it used to be the only endpoint relating to trades
They added other endpoints way later

I feel like the best compromise is to do something like this:
- Rename aggTrades to aggTrades (previously `trades`)
- Rename rawTrades to trade

This is the only solution I can think of that won't confuse a whole bunch of people, but still open to suggestions if we can think of something better

**Comment by dmitriz** [comment]
I would try to use exactly the same names as Binance, as the long term solution,
then the code can be simplified if names are the only difference,
all streams can be delegated to a single function.

Maybe a new version with this breaking change,
leaving the current one unchanged for everyone who is using it?

**Comment by dmitriz** [comment]
For the current version, if the alias identical with the Binance endpoint can be added,
that will be safe and future-proof. 

However, having both `trades` and `trade` in the same version can easily lead to more confusion, so perhaps not ideal.

**Comment by jaggedsoft** [comment]
Yes I am happy to make breaking changes anytime and will consider that. I suppose if someone files an issue we will already know what the problem is

**Comment by dmitriz** [comment]
You are welcome. No worries.

**Pull request merged**
