### PR TITLE
[Small edit] API update for userMarginData (outboundAccountPosition)

### PR DESCRIPTION
**Pull request by iyenal**
What the title says. Now uses 'outboundAccountPosition', please note that the modification has been already done for spot AccountInfo.

### CODE REVIEW

**Comment by iyenal** [comment]
If it can be pushed asap it would be great, as many projects rely on that (through npm). Thank you in advance.

**Comment by Yelles** [comment]
it would be very useful too, thank you! any update on merging this ?

**Comment by davidlondono** [comment]
assign the issue to @jaggedsoft

**Comment by iyenal** [comment]
Great, thanks.

**Pull request merged**
