### PR TITLE
Update node-binance-api.js

### PR DESCRIPTION
**Pull request by afsharsafavi**
Fixing POST method in "signedReqeust" function
@jaggedsoft  Be aware, I'm not expert at NodeJS, but because you said there is a problem like PHP in JavaScript (https://github.com/jaggedsoft/php-binance-api/pull/216#issuecomment-455519218), I changed some code, but I think my changes should be check by a Nodejs expert before merging to master repository.

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Thank you!

**Comment by afsharsafavi** [comment]
@jaggedsoft : It was OK?

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/issues/319

**Comment by jaggedsoft** [comment]
@afsharsafavi yes it was ok with a minor change, thank you friend.
https://github.com/jaggedsoft/node-binance-api/commit/ef3bc4bd8ee99a55ad5e72deb06e7f8310cc6fe3

**Comment by afsharsafavi** [comment]
@jaggedsoft : I make another changes in reqObj in https://github.com/jaggedsoft/node-binance-api/pull/320

**Comment by afsharsafavi** [comment]
@jaggedsoft : I made another changes in reqObj in #320 
I tested it and limit and marketbuy/sell work fine.

**Pull request merged**
