### PR TITLE
use of quoteOrderQty

### PR DESCRIPTION
**Pull request by polygxn**
props to this guy:
https://github.com/jaggedsoft/node-binance-api/issues/552#issuecomment-780031708

### CODE REVIEW

**Comment by heysyam99** [comment]
Still not merge yet?

**Comment by flolege** [comment]
Also waiting for merge here..

**Comment by heysyam99** [comment]
@flolege taking too long to merge so i decided to pull the project, and update it manually 😅

**Comment by heyimbrucelee** [comment]
@polygxn it would be nice to update docs too ;)

**Comment by jaggedsoft** [comment]
thank you!

**Comment by Lippa73** [comment]
could someone please show an example how I would structure the query after the code has been added?

**Comment by heysyam99** [comment]
hey @Lippa73, I believe you can pass parameter `quoteOrderQty` in order flags like this

```
const quantity = 0 // put anything here since this will be deleted if quoteOrderQty exists

const opt = {
   quoteOrderQty: 10
   // other option if needed
}

binance.marketBuy("BNBBTC", quantity, opt);
```

I think this snippet should work. Sorry, I haven't touched this in a while. Please update here if this is working. Thank you

**Comment by Lippa73** [comment]
thanks for the reply, I havent tried that format but I managed to get it working like this -

EDIT: I managed to solve it, in case anyone else is looking for it, this is the required syntax -

binance.marketBuy("BTCUSDT", quantity, {type:'MARKET', quoteOrderQty: amount}, function(error, response) {
console.info("Market Buy response", response);
console.info("order id: " + response.orderId);
});

quantity needs to be input, however it is ignored by the query

**Comment by heysyam99** [comment]
@Lippa73 yes, it should be working the same way. Thanks for the update.

**Pull request merged**
