### PR TITLE
Implement get/set futures positions side dual mode

### PR DESCRIPTION
**Pull request by abou7mied**
It's ok if you have better names for the functions, I just used the names of the API docs

### CODE REVIEW

**Comment by jaggedsoft** [comment]
thank you for your contribution. if you need a release immediately I will make one, otherwise it will be a few days

**Comment by abou7mied** [comment]
@jaggedsoft please release it if you can

I tried to use my Github repo for npm but it has some issues when installing inside docker

**Comment by jaggedsoft** [comment]
👍 
v0.11.11
⚡

**Comment by abou7mied** [comment]
Thanks for your quick response, I appreciate that

**Pull request merged**
