### PR TITLE
improved error handling

### PR DESCRIPTION
**Pull request by robaleman**
Not sure if this helps but forked Hem's error handling improvements and made a couple more adjustments:

- applied the error handling approach used in the publicrequest/apirequest/signedrequest methods to the prices and bookTickers methods 
- passed error msg to the callback functions
- fixed README so they reflected these changes

### CODE REVIEW

**Comment by jaggedsoft** [comment]
Looks great to me, thanks for your contributions!
I am extremely behind schedule and very little time to do testing, so I will rely on your word that everything is adequately tested and ready for release

**Comment by jaggedsoft** [comment]
Also thank you very much @hems for making this happen

**Comment by robaleman** [comment]
I did realize that I had neglected to pass the error to the callbacks in the balance method and the websockets. Patched those up real quick.

Afterwards, I ran all of the example calls and all of them seemed to be in good order, although I'm not exactly 100% sure how the testing feature works with the API so I'm still a little unsure if the buy/sell calls are going through or not.

Here's the test calls I use if someone else out there would like to double check. 
[test.js.zip](https://github.com/jaggedsoft/node-binance-api/files/1641775/test.js.zip)

**Comment by hems** [comment]
nice one

**Pull request merged**
