### PR TITLE
Set orderStatus to not force orderid, It can use the flags to find th…

### PR DESCRIPTION
**Pull request by WilliamStam**
Set orderStatus to not force orderid, It can use the flags to find the orderid / origClientOrderId as per the binance api information

as per https://github.com/jaggedsoft/node-binance-api/issues/669 

and

https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#query-order-user_data

### CODE REVIEW

**Comment by jaggedsoft** [comment]
thank you!

**Comment by sajuuk31** [comment]
Hello, code seems wrong as all2pie mentionned.

Today orderStatus just doesn't work as is.

**Comment by robprado-dev** [comment]
> Hello, code seems wrong as all2pie mentionned.
> 
> Today orderStatus just doesn't work as is.

Yes, it's not working 😕

**Comment by WilliamStam** [comment]
im really sorry :( i havent worked with this library for a while. and have no clue where to start with it again. 

i dont think the issues you facing are from this change (check the committed changes they are minimal). did binance change their api or something?

**Pull request merged**
